name: flutter_fruits
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flame:
  shared_preferences:
  flutter_launcher_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audio/sfx/bomb_explode.wav
    - assets/audio/sfx/swipe.wav
    - assets/audio/bgm/home.mp3
    - assets/audio/bgm/playing.mp3
    - assets/audio/sfx/haha2.ogg
    - assets/images/bg/backyard.png
    - assets/images/bg/lose-splash.png
    - assets/images/branding/title.png
    - assets/images/branding/logo.png
    - assets/images/fruits/bomb.png
    - assets/images/fruits/banana.png
    - assets/images/fruits/banana-cut-1.png
    - assets/images/fruits/banana-cut-2.png
    - assets/images/fruits/pineapple.png
    - assets/images/fruits/pineapple-cut-1.png
    - assets/images/fruits/pineapple-cut-2.png
    - assets/images/fruits/melancia.png
    - assets/images/fruits/melancia-cut-2.png
    - assets/images/fruits/melancia-cut-1.png
    - assets/images/fruits/melon_splash.png
    - assets/images/fruits/banana-splash.png
    - assets/images/ui/icon-help.png
    - assets/images/ui/icon-music-disabled.png
    - assets/images/ui/icon-music-enabled.png
    - assets/images/ui/icon-sound-disabled.png
    - assets/images/ui/icon-sound-enabled.png
    - assets/images/ui/start-button.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/branding/logo.png"